# Build docker image

name: CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to dockerhub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build backend docker image
        run: docker build -f apps/http/Dockerfile.backend -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }} .

      - name: Push docker image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection
        run: |
          printf "%s" "${{ secrets.SSH_PEM }}" > PRIVATE_KEY
          chmod 600 PRIVATE_KEY
          ssh -i PRIVATE_KEY -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }}@${{ secrets.HOST_IP }} << 'EOF'  
            echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker system prune -af --volumes 

            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

            docker run --name backend -d -e DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
          EOF
