# Steps -
# Checkout latest code
# Build docker image
# Publish image
# SSH into VM, pull latest image and start container

name: CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} -f apps/web/Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} .

      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection
        run: |
          printf "%s" "${{ secrets.SSH_PEM }}" > PRIVATE_KEY
          chmod 600 PRIVATE_KEY
          ssh -i PRIVATE_KEY -o StrictHostKeyChecking=no ${{ secrets.HOST_NAME }}@${{ secrets.HOST_IP }} << 'EOF'  
            echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Stop and remove only the frontend container
            docker stop frontend || true
            docker rm frontend || true

            # Remove only old frontend images
            docker images "${{ secrets.DOCKER_USERNAME }}/frontend" -q | xargs -r docker rmi -f || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

            docker run --name frontend -d -e "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          EOF
